apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: lycantropo/node-api
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector: #selector es la forma en la cual yo colsulto permitir ingreso al cluster 3000, buscar el nodo y decir que le aña
    app: api
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000