apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  labels:
    app: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: lycantropo/node-ui
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ui
spec:
  selector: #selector es la forma en la cual yo colsulto
    app: ui
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3030
    targetPort: 3030